# Generated by Django 5.1.15 on 2026-03-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Estimated hours to complete', max_digits=5, null=True),
        ),
    ]
